apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  retention: 90d
  retentionSize: 45GB
  storage:
    volumeClaimTemplate:
      spec:
#        accessModes: [ "ReadWriteOnce" ]
#        storageClassName: rbd
        resources:
          requests:
            storage: 50Gi
        selector:
          matchLabels:
            prometheus: hostpath
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  image: quay.io/prometheus/prometheus:v2.27.1
  containers:
  - name: prometheus
    livenessProbe:
      periodSeconds: 20
      timeoutSeconds: 5
  nodeSelector:
    kubernetes.io/hostname: node4
  tolerations:
  - effect: NoSchedule
    operator: Exists
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: v2.27.1
